// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchFileTree() {
  return window['go']['main']['App']['FetchFileTree']();
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}
