// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchFileTree():Promise<Array<main.FileNode>>;

export function Open(arg1:string):Promise<string>;
